### ISSUE TITLE
Charm PC casting lifetap or detrimental spell while charmed causing zone crash

### ISSUE THREAD

**Issue by nolangreene** [EQEmu/Server#1036] opened 2020-04-15 02:27 UTC
Issue is steadily reproducable when a PC is charmed by Pixtt Suir Mindrider and casts a lifetap or nuke and then has charm fade (theory) mid cast.

Below are 4 examples, notice the spell_ID is a lifetap or nuke. Every time the character casting the nuke was charmed, and speculatively breaking charm before the spell finished, the zone would crash.

The issue seems to happen when QueuePacket is called, and my guess is it's based on the owner becoming ambiguous from charm falling, not sure though.

More crash logs available on request (have 20+ from mindrider)

[crash_yxtta_version_0_inst_id_2825_port_7000_25387.log](https://github.com/EQEmu/Server/files/4478793/crash_yxtta_version_0_inst_id_2825_port_7000_25387.log)
[crash_yxtta_version_0_inst_id_2825_port_7021_28369.log](https://github.com/EQEmu/Server/files/4478794/crash_yxtta_version_0_inst_id_2825_port_7021_28369.log)
[crash_yxtta_version_0_inst_id_2825_port_7030_19978.log](https://github.com/EQEmu/Server/files/4478795/crash_yxtta_version_0_inst_id_2825_port_7030_19978.log)
[crash_yxtta_version_0_inst_id_2825_port_7070_26510.log](https://github.com/EQEmu/Server/files/4478796/crash_yxtta_version_0_inst_id_2825_port_7070_26510.log)

**Comment by mackal** [comment] 2020-04-15 02:41
Owner should be able to change during a call like that. So it's not the cause, but that code is ahhh special ...

**Comment by nolangreene** [comment] 2020-04-15 14:05
That's what I was thinking, but it's consistently repro-able with those conditions, so I'm not sure what other theories make sense.

**Comment by alimalkhalifa** [comment] 2020-04-17 05:23
I will take a look at this. I made a recent change that affects pets with regards to lifetap, nukes, and DoTs.

Might be the culprit. Or if it's not at least the code is still fresh in my mind

**Comment by alimalkhalifa** [comment] 2020-04-17 05:36
Note to self: is it trying to send a packet to mindrider or to a null owner around the hasOwner check?

**Comment by alimalkhalifa** [comment] 2020-04-19 05:42
@mackal could you close this issue please

**Closed** 2020-04-19 05:43 UTC
