### ISSUE TITLE
Having a different target than your pet results in the HP bar for the pet's target not being updated.

### ISSUE THREAD

**Issue by MidnightMusicClub** [EQEmu/Server#1768] opened 2021-11-15 16:33 UTC
In order to get the HP bar for the pet's target to update properly the player must have the same target. RoF2 client.

**Comment by KayenEQ** [comment] 2022-01-31 20:07
Couldn't reproduce this.

**Comment by noudess** [comment] 2022-01-31 20:35
I've seen this on and off as well.  Perhaps it's a distance thing if the pet is farther away?  I'll try and watch for it.

**Comment by MidnightMusicClub** [comment] 2022-01-31 20:39
I can't not reproduce it. Send pet on target, switch to a different target with the player and the HP bar for the mob the pet is fighting will not update anymore. Switch back to the pet's target and it will update. I just don't think it updates at all if the player doesn't have the same target.

**Comment by noudess** [comment] 2022-02-06 14:40
Ok, so I saw this twice today.

Low on HP, my beastlord set her pet into kill while she bound wounds.

This situation occurred twice.  Maybe it's distance?  

The pet window showed the opponent at full HP and the opponent eventually ran and died and the HP updated.  The opponent was running toward me both times.

Does this help?

**Comment by KayenEQ** [comment] 2022-02-09 02:03
No, only because nothing I am doing is reproducing it for me.

**Comment by MidnightMusicClub** [comment] 2022-02-09 16:54
Weird. It is broken on my server. If someone has a different target than their pet, the HP bar for the pet's target will not update no matter what until the pet's target dies or the player switches back to the pet's target. Once the player switches to the pet's target the HP bar jumps to it's current position.

**Comment by Kinglykrab** [comment] 2023-01-02 00:44
Closing for now, if more information becomes available or we find a way to reproduce, we can reopen in the future.

**Closed by Kinglykrab** 2023-01-02 00:44 UTC
Labels: Bug, Cannot Replicate Issue
