### ISSUE TITLE
GetNPCSpells miss too high spell ID value

### ISSUE THREAD

**Issue by moguay** [EQEmu/Server#893] opened 2019-09-06 19:57 UTC
The DBnpcspells_entries_Struct miss value up to 32767 and the spell_list->entries.spellid return an negative value instead of the spell id.

Probably need to change int16 spellid; for an unsigned var type.

File zonedb.h
#pragma pack(1)
struct DBnpcspells_entries_Struct {
	int16	spellid;
	uint8	minlevel;
	uint8	maxlevel;
	uint32	type;
	int16	manacost;
	int16	priority;
	int32	recast_delay;
	int16	resist_adjust;
	int8	min_hp;
	int8	max_hp;
};
#pragma pack()

**Comment by mackal** [comment] 2019-09-06 20:35
Yeah, even changing that isn't gonna fix all the issues, we need to switch all of our spellid references to just straight ints eventually. There is a ton of code that uses uint16 for some reason -.-

**Comment by mackal** [comment] 2019-09-09 03:56
Duplicate of #7

**Comment by Kinglykrab** [comment] 2021-10-03 00:55
Fixed here: https://github.com/EQEmu/Server/commit/e6dee96266b68a650360a599dc21b830e4c2ee23

**Closed by Kinglykrab** 2021-10-03 00:55 UTC
